resource_types:
    - name: git-branch
      type: docker-image
      source:
          repository: nmckinley/concourse-git-resource

resources:
    - name: magic-modules
      type: git
      source:
          uri: git@github.com:ndmckinley/magic-modules.git
          branch: master
          private_key: ((repo_key))

    - name: terraform-intermediate
      type: git-branch
      source:
          uri: git@github.com:ndmckinley/terraform-provider-google.git
          private_key: ((repo_key))

    - name: ci
      type: git
      source:
          uri: git@github.com:ndmckinley/terraform-provider-google-ci.git
          branch: git-pull-resource
          private_key: ((repo_key))

jobs:
    - name: mm-generate
      plan:
          - aggregate:
              - get: magic-modules
                params:
                    submodules: [build/terraform]
              - get: ci
          - task: generate
            file: ci/magic-modules/generate.yml
          - put: terraform-intermediate
            params:
                repository: mm-output/build/terraform
                tag: mm-output/tag
                branchfile: mm-output/branchname
                # The contents of this repo do not matter - this is just a place to
                # store the submodules of magic-modules so that the commit to
                # magic-modules can reference it during testing / before
                # the pull requests are ready.  Since each commit is tagged,
                # and each magic-modules commit points to a tag & hash rather than
                # a branch, `git gc` won't remove commits that are "overwritten"
                # with a force push, and the `magic-modules` branch pointer isn't
                # useful for anything other than getting this push to talk to
                # the output of the above `generate` step.  All this to say we can
                # safely force-push here.
                force: true
          # This needs to go below all the submodules because it has a commit which
          # points to those submodules.
          - put: magic-modules
            params:
                repository: mm-output
                branchfile: mm-output/branchname
                tag: mm-output/tag

    - name: terraform-test
      plan:
          - aggregate:
              - get: ci
              - get: magic-modules
                params:
                    submodules: [build/terraform]
                passed: [mm-generate]
          - task: test
            file: ci/unit-tests/task.yml

    - name: create-prs
      plan:
          - aggregate:
              - get: ci
              - get: magic-modules
                params:
                    submodules: [build/terraform]
                passed: [terraform-test]
          - task: create-prs
            file: ci/create-prs/task.yml
